### ISSUE TITLE
Idea de actualización de los datos cada x tiempo

### ISSUE THREAD

**Issue by Juansecod** [datorres1108/api.covid#1]
Hola David, viendo tu código se me ocurrió la idea con el método setInterval() se actualicen los datos y así digamos que no se tiene que estar dándole F5 o actualizando la pagina para tener los datos actualizados.

Solo seria cambiar la ultima lineal de código de la siguiente forma (voy a realizar en el ejemplo cada 10 segundos):

 `setInterval(informacionCivid(), 10000);`

Y por ultimo ya como FeedBack, seria renombrar las funciones, esto debido a comúnmente se usan las mayúsculas en la primera letra son en las clases.

**Comment by datorres1108** [comment]
Hola Juan como estas, muchas gracias por tu sugerencia esta perfecta, pero sabes veo que se presenta un problema con setInterval ya que este no juega bien con las promesas si no se detiene ya que las promesas solo pueden resolverse una vez, en estos casos si queremos usar  setInterval(), setTimeout() debemos de proporciona la lógica correcta en este caso seria despues de que resuelva la promesa aplicar un  clearInterval()  que borra el temporizador configurado con el método  setInterval() pero no la ejecuta.
Si lo dejamos solo con el   setInterval() cada 10 seg nos retornara un  Uncaught SyntaxError: Unexpected identifier
![image](https://user-images.githubusercontent.com/75844442/116908129-2bd49500-ac08-11eb-9838-d2d743a43916.png)

Para este caso mas puntual aunque no es el mas adecuado y para evitar el F5 del usuario final se puede resolver con la etiqueta Html <meta http-equiv="refresh" content="60"> la cual realiza un refresco al DOM cada minuto en este caso puntual le puse 300 segundos para cada 5 min.

Para el tema de las variables excelente y gracias por ese feedback, ya mismo las organizo, y si encuentras otra manera de como podamos solucionar el tema de las promesas para  setInterval()  sin utilizar la etiqueta de encabezado de DOM quedo atento.
Muchas gracias por tus comentarios y retroalimentación!!
